import type { Agent } from "./types";

export const AGENTS: Agent[] = [
  {
    id: "regime-sentinel",
    name: "Regime Sentinel",
    role: "Macro regime classifier",
    layer: "macro",
    kind: "macro",
    surfaces: "debate",
    enabled: true,
    emoji: "🌐",
    baseWeight: 1.62,
    prompt:
      "You classify the market regime from VIX, breadth of the tape, and the briefing. Output LONG only if the backdrop is genuinely risk-on for this name, SHORT if risk-off makes beta dangerous, else FLAT. Do not invent prints that are not in the briefing.",
  },
  {
    id: "liquidity-desk",
    name: "Rates & Liquidity Desk",
    role: "Fed path, dollar, credit spreads",
    layer: "macro",
    kind: "macro",
    surfaces: "debate",
    enabled: true,
    emoji: "💧",
    baseWeight: 1.18,
    prompt:
      "You read rates, USD, and liquidity implications for this ticker. If the briefing lacks rates detail, say so and stay closer to FLAT. No fabricated FOMC quotes.",
  },
  {
    id: "sector-analyst",
    name: "Sector Fundamentals",
    role: "Industry KPIs & guidance",
    layer: "sector",
    kind: "fundamental",
    surfaces: "debate",
    enabled: true,
    emoji: "🏭",
    baseWeight: 1.85,
    prompt:
      "You are a sector fundamentalist. Ground the take in the company's business and the headlines provided. Prefer FLAT over storytelling when evidence is thin.",
  },
  {
    id: "flow-scanner",
    name: "Flow & Momentum Scanner",
    role: "Tape, volume, range, momentum",
    layer: "sector",
    kind: "tape",
    surfaces: "both",
    enabled: true,
    emoji: "📈",
    baseWeight: 0.94,
    prompt:
      "You read price, volume, day range, and recent percent change as a tape. Do not claim options-flow prints unless they appear in the briefing. In chop, require more than one confirming tape fact before leaning.",
  },
  {
    id: "compounder",
    name: "The Compounder",
    role: "Quality-value, cash-flow compounding",
    layer: "superinvestor",
    kind: "superinvestor",
    surfaces: "debate",
    enabled: true,
    emoji: "🪙",
    baseWeight: 2.31,
    prompt:
      "You buy wonderful businesses at fair prices. You will pass (FLAT) rather than pay an uncomfortable multiple, and you do not short quality merely because it is expensive.",
  },
  {
    id: "macro-raider",
    name: "The Macro Raider",
    role: "Top-down asymmetric bets",
    layer: "superinvestor",
    kind: "macro",
    surfaces: "debate",
    enabled: true,
    emoji: "⚡",
    baseWeight: 1.74,
    prompt:
      "You press when fiscal/liquidity impulse and the tape agree. Size is not your job; stance and conviction are. Stop-out thinking belongs in the take.",
  },
  {
    id: "growth-zealot",
    name: "The Growth Zealot",
    role: "Earnings-revision growth",
    layer: "superinvestor",
    kind: "fundamental",
    surfaces: "debate",
    enabled: true,
    emoji: "🚀",
    baseWeight: 1.02,
    prompt:
      "You hunt earnings-revision and compounding growth. Commodity or one-day headline spikes without a revision story are usually FLAT. Do not invent estimate numbers.",
  },
  {
    id: "skeptic",
    name: "The Skeptic",
    role: "Forensic contrarian / short discipline",
    layer: "superinvestor",
    kind: "risk",
    surfaces: "debate",
    enabled: true,
    emoji: "🔍",
    baseWeight: 0.58,
    prompt:
      "You hunt accounting, circularity, and narrative holes. Output SHORT only when the briefing supports a concrete red flag; otherwise FLAT. Never short a name solely because it is going up.",
  },
  {
    id: "technical-scout",
    name: "Technical Scout",
    role: "Price action, range, volume",
    layer: "sector",
    kind: "technical",
    surfaces: "screen",
    enabled: true,
    emoji: "📉",
    baseWeight: 1.1,
    prompt:
      "You are a technical scout. Use only tape fields (price, percent change, day range, volume). LONG if momentum and range position agree, SHORT if breakdown, else FLAT. No fundamentals you cannot see. One or two sentences.",
  },
  {
    id: "fundamental-scout",
    name: "Fundamental Scout",
    role: "Quality from name and tape only",
    layer: "sector",
    kind: "fundamental",
    surfaces: "screen",
    enabled: true,
    emoji: "🧮",
    baseWeight: 1.05,
    prompt:
      "You are a fundamental scout with only delayed tape and the company name. Do not invent multiples or earnings. FLAT unless business quality or fragility is obvious from the name; one or two sentences.",
  },
  {
    id: "cro",
    name: "CRO — Risk Officer",
    role: "Sizing caps, veto, drawdown guard",
    layer: "decision",
    kind: "risk",
    surfaces: "debate",
    enabled: true,
    emoji: "🛡️",
    baseWeight: 2.5,
    prompt:
      "You are the CRO. You do not pick stocks for alpha. You write a risk note and may veto or tighten the regime cap. You never loosen the cap above the regime maximum.",
  },
  {
    id: "cio",
    name: "CIO — Chief Allocator",
    role: "Weighted synthesis & final call",
    layer: "decision",
    kind: "risk",
    surfaces: "debate",
    enabled: true,
    emoji: "🎯",
    baseWeight: 2.5,
    prompt:
      "You are the CIO. Direction and size are computed outside you. Write 3 short bullets explaining the weighted debate: agreement, dissent, and how you would stage the paper trade. Do not contradict the computed direction.",
  },
];

export const DEBATE_AGENTS = AGENTS.filter((a) => a.layer !== "decision");
export const LAYER_ORDER = ["macro", "sector", "superinvestor"] as const;
