import type { Settings } from "./shared/types";

const STR = {
  tr: {
    tag: "kâğıt araştırma masası",
    screener: "Screener",
    settings: "Ayarlar",
    history: "Geçmiş",
    logout: "Çıkış",
    price: "Fiyat çek",
    debate: "▶ TARTIŞ",
    debating: "⏳ TARTIŞILIYOR…",
    book: "KÂĞIDA YAZ",
    booked: "✓ KÂĞIDA YAZILDI",
    mark: "Seansı işaretle",
    reset: "Sıfırla",
    close: "Kapat",
    empty: "Tartışma katı boş.",
    emptyHint: "Bir ticker yaz, fiyatı çek, sonra OpenRouter üzerinden gerçek katmanlı tartışmayı çalıştır.",
    noKey: "OpenRouter anahtarı yok. Ayarlar’dan yapıştır veya OPENROUTER_API_KEY ile başlat. Sahte take üretilmez.",
    paper: "Kâğıt defter",
    cash: "KASA",
    equity: "ÖZSERMAYE",
    gross: "BRÜT",
    net: "NET",
    none: "Açık pozisyon yok.",
    closed: "Kapanan",
    journal: "Günlük",
    status: "Durum",
    weights: "Darwin ağırlıkları",
    dueNone: "Vadesi gelen tartışma yok.",
    marked: "işaretlendi",
    confirmClose: "Pozisyon kapatılsın mı?",
    gate: "kâğıt araştırma masası · giriş gerekli",
    password: "KAPI ŞİFRESİ",
    enter: "Giriş",
    keyOn: "OpenRouter tanımlı",
    keyOff: "API key yok",
    disclaimer: "Kâğıt defter + araştırma masası. Canlı broker yok. Yatırım tavsiyesi değildir.",
  },
  en: {
    tag: "paper research desk",
    screener: "Screener",
    settings: "Settings",
    history: "History",
    logout: "Log out",
    price: "Fetch price",
    debate: "▶ RUN DEBATE",
    debating: "⏳ DEBATING…",
    book: "BOOK TO PAPER",
    booked: "✓ BOOKED",
    mark: "Mark session",
    reset: "Reset",
    close: "Close",
    empty: "The floor is empty.",
    emptyHint: "Type a ticker, fetch the price, then run a real layered debate through OpenRouter.",
    noKey: "No OpenRouter key. Paste one in Settings or start with OPENROUTER_API_KEY. No fake takes.",
    paper: "Paper book",
    cash: "CASH",
    equity: "EQUITY",
    gross: "GROSS",
    net: "NET",
    none: "No open positions.",
    closed: "Closed",
    journal: "Journal",
    status: "Status",
    weights: "Darwinian weights",
    dueNone: "No debates are due.",
    marked: "marked",
    confirmClose: "Close this position?",
    gate: "paper research desk · sign in",
    password: "GATE PASSWORD",
    enter: "Enter",
    keyOn: "OpenRouter set",
    keyOff: "No API key",
    disclaimer: "Paper book and research desk. No live broker. Not investment advice.",
  },
} as const;

export type CopyKey = keyof typeof STR.tr;

export function tx(lang: Settings["language"], key: CopyKey): string {
  return STR[lang][key];
}
